{
 "title": "fastapi visualization",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(up{job=~\"myapp|prometheus\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((increase(http_requests_total{job=~\"$job\",status_code=~\"4..\"}[$__range])) or vector(0)) + sum((increase(http_requests_total{job=\"$job\",status_code=~\"5..\"}[$__range])) or vector(0))) /sum(increase(http_requests_total{job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_sum[30m]))/sum (rate(http_request_duration_seconds_count[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "API throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"myapp\"}[5m])",
     "legendFormat": "{{method}} {{endpoint}} {{status_code}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Requests by status code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(http_requests_total{job=\"myapp\"}[5m])) by (status_code)",
     "legendFormat": "status {{status_code}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "API latency percentile",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[5m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_request_duration_seconds_bucket{job=\"myapp\"}[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": " (rate(http_request_duration_seconds_sum{endpoint=~\"^(/|/submit|/update)$\"}[5m]))/(rate(http_request_duration_seconds_count{endpoint=~\"^(/|/submit|/update)$\"}[5m]))",
     "legendFormat": "{{endpoint}} {{method}} {{status_code}}"
    }
   ]
  },
  { "title": "system metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU USAGE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"myapp\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"myapp\"}/process_max_fds{job=\"myapp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (in MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"myapp\"}/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{job=\"myapp\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}